[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
script = 'forge-script'
test = 'forge-test'
cache_path  = 'cache_forge'
fs_permissions = [{ access = "read", path = "./"}]
remappings = [
    "solady/=lib/solady/",
    "p256-verifier/=lib/p256-verifier-fork/src/"
]
solc = "0.8.21"
optimizer_enabled=true
optimizer_runs=999999
via_ir=true